import { cn } from "@/libs/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import AuthContextProvider from "./context/AuthContext";
import ToasterContext from "./context/ToasterContext";
import Providers from "@/components/Providers";
import "react-loading-skeleton/dist/skeleton.css";
import { Toaster } from "@/components/ui/toaster";
import "simplebar-react/dist/simplebar.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-sans antialiased grainy",
          inter.className
        )}
      >
        <AuthContextProvider>
          <Providers>
            <ToasterContext></ToasterContext>
            <Toaster></Toaster>
            <Navbar></Navbar>
            {children}
          </Providers>
        </AuthContextProvider>
      </body>
    </html>
  );
}
